subdir = src/backend/access/tile
top_builddir = ../../../..
CC = g++

include $(top_builddir)/src/Makefile.global

OBJS = tileam.o tileam_handler.o tileutils.o

include $(top_srcdir)/src/backend/common.mk
